### ISSUE TITLE
When selecting a font, hitting return doesn't select it

### ISSUE THREAD

**Issue by thedoglett** [Log1x/laravel-webfonts#42]
I've installed this on a Laravel 11 project (this is my composer file):

```
"log1x/laravel-webfonts": "^1.0",
```

and have run:

```
php artisan webfonts:add
```
When I do this and hit return I get the message:
```
 ⚠ You must select at least one font.
```
I'm using  PHP Storm's terminal so I tried it on my Mac (Sequoia) Terminal and had the same issue.

Then I tried it on Nova's terminal and had the same problem.

This is what happens:

https://github.com/user-attachments/assets/7275eae7-a1c9-4acb-8c4f-924a15bc91b6

I'm using a MacBook Pro 16" (2019) with a European keyboard; I've also tried it with two Logitech MX Keys keyboards and the issue persists. I've tried both return keys(main keyboard and the numeric pad) but no luck.

Obviously the return key works when I installed the package (and for other terminal commands) which is making me wonder if there's an issue with the interface for selecting fonts since I can replicate it (albeit on the same machine) on multiple terminal applications.

Can you assist at all?

If you need any other information please don't hesitate to ask.

Many thanks (and a Happy New Year!).

**Comment by Log1x** [comment]
Does it let you select them with spacebar?

**Comment by thedoglett** [comment]
Aha, yes that worked. Of all the key combinations I tried, that's the one I didn't - probably too much 🍺🍺🍺 over Christmas break affecting the old grey matter!

Thanks for your prompt reply. 👍

**Comment by Log1x** [comment]
Sweet! Glad it worked. No problem :)
